name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/your-repo-name:latest
      
      # - name: Add server to known_hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      #     chmod 600 ~/.ssh/known_hosts    

      # - name: SSH Deploy to Server
      #   uses: garygrossgarten/github-action-ssh@v0.6.3
      #   with:
      #     command: |
      #       docker pull ghcr.io/${{ github.repository_owner }}/your-repo-name:latest
      #       docker stop your-container-name || true
      #       docker rm your-container-name || true
      #       docker run -d --name your-container-name -p 3000:3000 ghcr.io/${{ github.repository_owner }}/your-repo-name:latest
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     privateKey: ${{ secrets.SERVER_SSH_KEY }}
      - name: Set image name 2
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-repo-name:latest" >> $GITHUB_ENV

      - name: Display Image Name
        run: |
          echo "Image name $IMAGE_NAME"

      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
            # hostname / IP of the server
            # docker pull env.IMAGE_NAME
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          private_key: ${{ secrets.SERVER_SSH_KEY }}
          host_fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          args: IMAGE_NAME
          command: |
            docker pull ghcr.io/matou-de-lune/your-repo-name:latest
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d --name your-container-name -p 3000:3000 $IMAGE_NAME
