name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/your-repo-name:latest
      
      # - name: Set image name 2
      #   run: |
      #     echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/your-repo-name:latest" >> $GITHUB_ENV
      #     echo "CR_PAT=${{ secrets.CR_PAT }}" >> $GITHUB_ENV

      # - name: Display Image Name
      #   run: |
      #     echo "Image name $IMAGE_NAME"

      - name: SSH Command
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          private_key: ${{ secrets.SERVER_SSH_KEY }}
          host_fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          command: |
            docker pull ghcr.io/${{ github.repository_owner }}/your-repo-name:latest; 
            docker stop your-container-name || true; 
            docker rm your-container-name || true; 
            docker run -d --name your-container-name -p 3000:3000 ghcr.io/${{ github.repository_owner }}/your-repo-name:latest

# cat ~/cod.txt | docker login ghcr.io -u ${{ github.actor }} --password-stdin;      

      - name: Authenticate and Delete Docker package from GitHub Container Registry1
        uses: actions/delete-package-versions@v5
        with:
          owner: 'github'
          package-name: 'your-repo-name'
          package-type: 'docker'
          token: ${{ secrets.CR_PAT }}
          min-versions-to-keep: 1

      # - name: Authenticate and Pull Docker Image on RemoteServer
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     fingerprint: ${{ secrets.SSH_FINGERPRINT }}
      #     # port: 22
      #     envs: IMAGE_NAME, GHCR_TOKEN=${{ secrets.GHCR_TOKEN }}
      #     script: |
      #       echo $GHCR_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      #       docker pull $IMAGE_NAME
      #       docker stop your-container-name || true
      #       docker rm your-container-name || true
      #       docker run -d --name your-container-name -p 3000:3000 $IMAGE_NAME      

            

# docker stop your-container-name || true
#             docker rm your-container-name || true
#             docker run -d --name your-container-name -p 3000:3000 $IMAGE_NAME            
            # echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                        # docker pull ghcr.io/matou-de-lune/your-repo-name:latest
                        # sourse ~/.nvm/nvm.sh; ~/deploy.sh